CREATE TABLE `t_city_info` (
  `Farea_id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '城市ID',
  `Fparent_id` int(10) unsigned DEFAULT '0' COMMENT '上级城市ID',
  `Farea_name` char(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '城市名称',
  `Fall_name` char(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '城市全称',
  `Ffirst_letter` char(1) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '名称首字母',
  `Fcity_jianpin` char(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '城市简拼',
  `Fcity_qp` char(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '城市全拼',
  `Fcity_level` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '城市级别',
  `Fcity_path` varchar(256) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT ' 城市路径',
  `Fcity_msg` char(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '城市信息(备注)',
  `Fcreate_time` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '创建时间',
  `Fupdate_time` int(10) unsigned DEFAULT '0' COMMENT '更新时间',
  `Fcity_status` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '城市状态信息, 1:启用,2:停用,99:删除',
  `Fprovince_id` char(12) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '省会id',
  `Fcity_id` char(12) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '城市id',
  `Fcounty_id` char(12) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '县id',
  `Fauto_update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '变更时间',
  PRIMARY KEY (`Farea_id`),
  KEY `FKcityStatus` (`Fcity_status`),
  KEY `FKparentId` (`Fparent_id`)
) ENGINE=InnoDB AUTO_INCREMENT=820200101 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='地区表(主要数据来源于国家统计局并作清洗)';
